version: '2'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "6000:6000"
    environment:
      POSTGRES_USER: jamesbond
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
